#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

([ -z \"$SKIP_HOOK\" ] && sanity-template lockfiles && git add '*package-lock.json*' && git diff --quiet && SKIP_HOOK=1 git commit -m 'chore: generate lockfiles') && echo 'Committed lockfiles' || echo ''
